const stage=document.getElementById('stage'),nodesLayer=document.getElementById('nodes'),svg=document.getElementById('links'),msg=document.getElementById('message'),pill=document.getElementById('statusPill');
let nodes=[],links=[],selected=null,count=0;
const defs={pc:{icon:'💻',name:'パソコン',sub:'有線端末'},phone:{icon:'📱',name:'スマートフォン',sub:'Wi-Fi端末'},hub:{icon:'▦',name:'ハブ',sub:'LAN内を接続'},ap:{icon:'◉',name:'アクセスポイント',sub:'無線→LAN'},router:{icon:'⇄',name:'ルータ',sub:'LAN↔WAN'}};
function say(t,type=''){msg.className='message '+type;msg.textContent=t}
function addNode(type){count++;let d=defs[type],el=document.createElement('div');el.className='node';el.dataset.id='n'+count;el.dataset.type=type;el.innerHTML=`<span class="ico">${d.icon}</span><b>${d.name}</b><small>${d.sub}</small>`;let x=45+(nodes.length%4)*135,y=70+Math.floor(nodes.length/4)*105;el.style.left=x+'px';el.style.top=y+'px';nodesLayer.appendChild(el);nodes.push({id:el.dataset.id,type,el});drag(el);el.addEventListener('click',e=>{e.stopPropagation();choose(el)});say(`${d.name}を追加しました。もう1台追加して、2つの機器を順にクリックすると接続できます。`);updatePill()}
function choose(el){if(!selected){selected=el;el.classList.add('selected');say(`${defs[el.dataset.type].name}を選択中。接続したい機器をクリックしてください。`);return}if(selected===el){selected.classList.remove('selected');selected=null;return}let a=selected.dataset.id,b=el.dataset.id;if(!links.some(l=>(l.a===a&&l.b===b)||(l.a===b&&l.b===a)))links.push({a,b});selected.classList.remove('selected');selected=null;draw();say('機器を接続しました。通信ボタンでデータの流れを確認できます。','ok');updatePill()}
function drag(el){let sx,sy,ox,oy,moved=false;el.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY;ox=parseFloat(el.style.left);oy=parseFloat(el.style.top);moved=false;el.setPointerCapture(e.pointerId)});el.addEventListener('pointermove',e=>{if(!el.hasPointerCapture(e.pointerId))return;if(Math.abs(e.clientX-sx)+Math.abs(e.clientY-sy)>5)moved=true;let x=Math.max(5,Math.min(stage.clientWidth*.60-el.offsetWidth,ox+e.clientX-sx));let y=Math.max(48,Math.min(stage.clientHeight-el.offsetHeight-5,oy+e.clientY-sy));el.style.left=x+'px';el.style.top=y+'px';draw()});el.addEventListener('pointerup',e=>el.releasePointerCapture(e.pointerId))}
function center(id){let n=nodes.find(n=>n.id===id).el;return{x:n.offsetLeft+n.offsetWidth/2,y:n.offsetTop+n.offsetHeight/2}}
function draw(){svg.innerHTML='';links.forEach(l=>{let a=center(l.a),b=center(l.b),ta=nodes.find(n=>n.id===l.a).type,tb=nodes.find(n=>n.id===l.b).type,wifi=ta==='phone'||tb==='phone';let line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y);line.setAttribute('stroke',wifi?'#06b6d4':'#2563eb');line.setAttribute('stroke-width','4');if(wifi)line.setAttribute('stroke-dasharray','8 7');svg.appendChild(line)})}
function neighbors(id){return links.flatMap(l=>l.a===id?[l.b]:l.b===id?[l.a]:[])}
function pathBetween(start,goalTest){let q=[[start]],seen=new Set([start]);while(q.length){let p=q.shift(),last=p[p.length-1];if(goalTest(last))return p;for(let n of neighbors(last))if(!seen.has(n)){seen.add(n);q.push([...p,n])}}return null}
function validEdge(a,b){let A=nodes.find(n=>n.id===a),B=nodes.find(n=>n.id===b);if(A.type==='phone'&&B.type!=='ap')return false;if(B.type==='phone'&&A.type!=='ap')return false;return true}
function validPath(p){return p&&p.every((x,i)=>i===0||validEdge(p[i-1],x))}
async function animatePath(path,toWan=false){document.querySelectorAll('.packet').forEach(x=>x.remove());let p=document.createElement('div');p.className='packet';stage.appendChild(p);let pts=path.map(center);if(toWan){let r=stage.getBoundingClientRect(),ir=document.getElementById('internet').getBoundingClientRect(),sr=document.getElementById('server').getBoundingClientRect();pts.push({x:ir.left-r.left+ir.width/2,y:ir.top-r.top+ir.height/2},{x:sr.left-r.left+sr.width/2,y:sr.top-r.top+sr.height/2})}for(let i=0;i<pts.length;i++){p.style.left=(pts[i].x-7)+'px';p.style.top=(pts[i].y-7)+'px';await new Promise(r=>setTimeout(r,i?600:100))}setTimeout(()=>p.remove(),700)}
function updatePill(){let r=nodes.some(n=>n.type==='router'),h=nodes.some(n=>n.type==='hub'),a=nodes.some(n=>n.type==='ap');pill.textContent=r?'ルータあり：WANへ出られる構成を確認':(h||a)?'LANの中心機器あり':'LANを作ってみよう'}
function flowActive(n){document.querySelectorAll('.flow-step').forEach((e,i)=>e.classList.toggle('active',i<n))}
document.querySelectorAll('.device-btn').forEach(b=>b.onclick=()=>addNode(b.dataset.type));stage.addEventListener('click',()=>{if(selected){selected.classList.remove('selected');selected=null}});
document.getElementById('clearLinks').onclick=()=>{links=[];draw();say('接続線を消しました。別の構成を試せます。')};
document.getElementById('resetBtn').onclick=()=>{nodes=[];links=[];count=0;nodesLayer.innerHTML='';svg.innerHTML='';flowActive(0);document.getElementById('explainBox').textContent='通信ボタンを押すと、ここに通信の流れが表示されます。';say('最初の状態に戻しました。');updatePill()};
document.getElementById('lanDemo').onclick=async()=>{let ends=nodes.filter(n=>['pc','phone'].includes(n.type));if(ends.length<2){say('LAN内通信を見るには、パソコンやスマートフォンを2台以上置いてください。','warn');return}let path=pathBetween(ends[0].id,id=>id!==ends[0].id&&ends.some(e=>e.id===id));if(!validPath(path)){say('まだ通信できません。スマートフォンはアクセスポイントへ、パソコンはハブなどへつなぎ、LAN内の道を作ってください。','warn');return}await animatePath(path);flowActive(2);say('LAN内でデータが届きました。LANの中だけなら、インターネットを通らず通信できます。','ok');document.getElementById('explainBox').innerHTML='<b>LAN内通信：</b> 端末から送られたデータは、ハブやアクセスポイントを通って同じLAN内の端末へ届きます。ルータやWANを通らない通信もあります。'};
document.getElementById('wanDemo').onclick=async()=>{let ends=nodes.filter(n=>['pc','phone'].includes(n.type)),router=nodes.find(n=>n.type==='router');if(!ends.length||!router){say('インターネットへ出るには「端末」と「ルータ」が必要です。機器を追加して接続してください。','warn');return}let path=pathBetween(ends[0].id,id=>id===router.id);if(!validPath(path)){say('端末からルータまでの道がつながっていません。スマホならアクセスポイントを経由させてください。','warn');return}await animatePath(path,true);flowActive(5);say('通信成功！ LAN → ルータ → WAN → Webサーバへデータが届きました。','ok');document.getElementById('explainBox').innerHTML='<b>インターネット通信：</b> 端末のデータはLAN内を進み、ルータがLANの外へ送り出します。その後WAN（インターネット）を通ってWebサーバへ届き、Webページのデータが戻ってきます。'};
window.addEventListener('resize',draw);
