const deviceInfo={hub:'🔀 <b>ハブ（スイッチングハブ）</b>：同じLAN内の複数の機器を有線でつなぎ、データを必要な相手へ届けます。',router:'📡 <b>ルータ</b>：LANとWANなど、異なるネットワーク同士をつなぎ、データをどこへ送るか判断します。',ap:'📶 <b>アクセスポイント（AP）</b>：スマホなどの無線機器をWi-FiでLANへ接続します。'};
document.querySelectorAll('.device-card').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.device-card').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('deviceInfo').innerHTML=deviceInfo[b.dataset.device]}));

const stage=document.getElementById('networkStage'),packet=document.getElementById('packet'),svg=document.querySelector('.links');
function center(id){const a=document.getElementById(id).getBoundingClientRect(),s=stage.getBoundingClientRect();return{x:a.left-s.left+a.width/2,y:a.top-s.top+a.height/2}}
function draw(){svg.innerHTML='';let pairs=[['pc','hub'],['phone','ap'],['ap','hub'],['hub','router1'],['router1','router2'],['router2','server']];pairs.forEach(([a,b])=>{let p=center(a),q=center(b),l=document.createElementNS('http://www.w3.org/2000/svg','line');Object.entries({x1:p.x,y1:p.y,x2:q.x,y2:q.y,stroke:'#8aa4ba','stroke-width':3,'stroke-dasharray':'7 5'}).forEach(([k,v])=>l.setAttribute(k,v));svg.appendChild(l)})}
window.addEventListener('load',draw);window.addEventListener('resize',draw);
const descriptions={pc:['PC','Webページを見たいPCが、データの送信を始めます。'],phone:['スマホ','スマホはまずWi-Fiでアクセスポイントへデータを送ります。'],ap:['アクセスポイント','無線のデータをLANへ橋渡しします。'],hub:['ハブ','同じLAN内で、データをルータへ届けます。'],router1:['学校のルータ','宛先が別ネットワークなので、WAN（インターネット）へ送り出します。'],router2:['相手側のルータ','WANから届いたデータを、相手側LANの正しい宛先へ送ります。'],server:['Webサーバ','データが目的地に到着しました。サーバは要求に応じてWebページのデータを返します。']};
let running=false;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function send(){if(running)return;running=true;document.getElementById('sendBtn').disabled=true;const source=document.getElementById('sourceSelect').value;const route=source==='pc'?['pc','hub','router1','router2','server']:['phone','ap','hub','router1','router2','server'];packet.style.display='grid';for(let i=0;i<route.length;i++){document.querySelectorAll('.node').forEach(n=>n.classList.remove('active'));const id=route[i],p=center(id);packet.style.left=(p.x-17)+'px';packet.style.top=(p.y-17)+'px';document.getElementById(id).classList.add('active');document.getElementById('statusTitle').textContent=`STEP ${i+1}：${descriptions[id][0]}`;document.getElementById('statusText').textContent=descriptions[id][1];document.getElementById('stepCount').textContent=`${i+1} / ${route.length}`;document.getElementById('progressBar').style.width=`${(i+1)/route.length*100}%`;await sleep(i===0?600:1050)}document.getElementById('statusTitle').textContent='✅ 通信成功！';document.getElementById('statusText').textContent='LAN → ルータ → WAN → ルータ → LAN とつながることで、離れた相手とも通信できます。';running=false;document.getElementById('sendBtn').disabled=false}
document.getElementById('sendBtn').addEventListener('click',send);document.getElementById('resetBtn').addEventListener('click',()=>{running=false;packet.style.display='none';document.querySelectorAll('.node').forEach(n=>n.classList.remove('active'));document.getElementById('statusTitle').textContent='通信を開始してみよう';document.getElementById('statusText').textContent='「通信してみる」を押すと、データ（パケット）が相手まで移動します。';document.getElementById('stepCount').textContent='0 / 0';document.getElementById('progressBar').style.width='0';document.getElementById('sendBtn').disabled=false});
const flow=[['💻📱','端末','データを作る'],['🔀📶','LAN内の機器','同じLAN内をつなぐ'],['📡','ルータ','別ネットワークへ'],['☁️','WAN','遠くまで運ぶ'],['📡','ルータ','相手LANへ'],['🗄️','サーバ','データを受け取る']];document.getElementById('flowSummary').innerHTML=flow.map((x,i)=>`<div class="flow-item"><span>${x[0]}</span><b>${x[1]}</b><br>${x[2]}</div>${i<flow.length-1?'<div class="arrow">→</div>':''}`).join('');
const qs=[{q:'スマホをWi-FiでLANにつなぐ機器は？',a:['ルータ','アクセスポイント','ハブ'],c:1},{q:'異なるネットワーク同士をつなぐ機器は？',a:['ルータ','アクセスポイント','ハブ'],c:0},{q:'学校内など限られた範囲のネットワークを何という？',a:['WAN','LAN','Web'],c:1}];let score=0,done=new Set();const quiz=document.getElementById('quiz');quiz.innerHTML=qs.map((q,i)=>`<div class="question"><p>Q${i+1}. ${q.q}</p><div class="answers">${q.a.map((a,j)=>`<button data-q="${i}" data-a="${j}">${a}</button>`).join('')}</div></div>`).join('');quiz.addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;let qi=+e.target.dataset.q,ai=+e.target.dataset.a;if(done.has(qi))return;done.add(qi);if(ai===qs[qi].c){e.target.classList.add('correct');score++}else{e.target.classList.add('wrong');e.target.parentElement.children[qs[qi].c].classList.add('correct')}if(done.size===qs.length)document.getElementById('quizResult').textContent=`${score} / ${qs.length} 問正解！ ${score===qs.length?'🎉 基本をしっかり理解できています。':'上の機器カードと通信の流れをもう一度確認してみよう。'}`});
